//Найти случайное число от 10 до 99 и определить наибольшую цифру в этом числе

Console.Clear();

int n = new Random().Next(10, 100); // generating a random number from 10 to 99
Console.WriteLine($"Случайное число: {n}"); //output of the number generated by the program
int n1 = n /10; // looking for a dozen of the number
int n2 = n % 10; // find the last digit of the number
if (n1 > n2)
    Console.Write(n1);
else
    Console.Write(n2);    
